import type { VoiceKey } from './voices';

export const SAMPLE_TEXTS: Record<VoiceKey, string> = {
  fr: `Notre-Dame de Paris, cathédrale gothique située sur l'île de la Cité au cœur de Paris, fut érigée entre 1163 et 1345 sous l'impulsion de l'évêque Maurice de Sully. Chef-d'œuvre de l'art médiéval, elle se distingue par ses arcs-boutants, ses gargouilles emblématiques et ses trois rosaces aux vitraux colorés. Au fil des siècles, elle a accueilli le sacre de Napoléon en 1804, inspiré Victor Hugo pour son roman immortel, et survécu à la Révolution française qui faillit la détruire. Le 15 avril 2019, un incendie dévastateur ravagea sa charpente et fit s'effondrer sa flèche, déclenchant un élan mondial de solidarité. Plus de huit cents millions d'euros furent collectés en quelques jours pour financer sa reconstruction. Cinq années de travaux minutieux mobilisèrent les meilleurs artisans français : charpentiers, tailleurs de pierre, maîtres verriers et facteurs d'orgues. Rouverte au public en décembre 2024, Notre-Dame accueille à nouveau des millions de visiteurs venus admirer sa flèche restaurée, ses vitraux retrouvés et son orgue monumental aux cinq claviers et huit mille tuyaux.`,
  en: `Notre-Dame de Paris, a Gothic cathedral located on the Île de la Cité in the heart of Paris, was built between 1163 and 1345 under the leadership of Bishop Maurice de Sully. A masterpiece of medieval art, it stands out for its flying buttresses, its iconic gargoyles, and its three rose windows with vibrant stained glass. Over the centuries, it hosted Napoleon's coronation in 1804, inspired Victor Hugo's timeless novel, and survived the French Revolution which nearly destroyed it. On April 15, 2019, a devastating fire ravaged its roof and caused its spire to collapse, sparking a worldwide wave of solidarity. More than eight hundred million euros were raised within days to finance its reconstruction. Five years of meticulous work mobilized the finest French craftsmen: carpenters, stonemasons, master glassmakers, and organ builders. Reopened to the public in December 2024, Notre-Dame once again welcomes millions of visitors who come to admire its restored spire, its recovered stained glass, and its monumental organ with five keyboards and eight thousand pipes.`,
  it: `Notre-Dame de Paris, cattedrale gotica situata sull'Île de la Cité nel cuore di Parigi, fu costruita tra il 1163 e il 1345 sotto la guida del vescovo Maurice de Sully. Capolavoro dell'arte medievale, si distingue per i suoi archi rampanti, le sue iconiche gargolle e i suoi tre rosoni dalle vetrate colorate. Nel corso dei secoli, ospitò l'incoronazione di Napoleone nel 1804, ispirò Victor Hugo per il suo immortale romanzo, e sopravvisse alla Rivoluzione francese che stava per distruggerla. Il 15 aprile 2019, un incendio devastatore distrusse la sua copertura e fece crollare la sua guglia, scatenando un'ondata mondiale di solidarietà. Oltre ottocento milioni di euro furono raccolti in pochi giorni per finanziare la ricostruzione. Cinque anni di lavori meticolosi mobilitarono i migliori artigiani francesi: carpentieri, scalpellini, mastri vetrai e organari. Riaperta al pubblico nel dicembre 2024, Notre-Dame accoglie nuovamente milioni di visitatori venuti ad ammirare la sua guglia restaurata, le sue vetrate ritrovate e il suo organo monumentale con cinque tastiere e ottomila canne.`,
  es: `Notre-Dame de París, catedral gótica situada en la Île de la Cité en el corazón de París, fue construida entre 1163 y 1345 bajo el impulso del obispo Maurice de Sully. Obra maestra del arte medieval, destaca por sus arbotantes, sus emblemáticas gárgolas y sus tres rosetones con vitrales coloridos. A lo largo de los siglos, acogió la coronación de Napoleón en 1804, inspiró a Victor Hugo para su novela inmortal, y sobrevivió a la Revolución Francesa que estuvo a punto de destruirla. El 15 de abril de 2019, un incendio devastador arrasó su tejado e hizo colapsar su aguja, desencadenando una ola mundial de solidaridad. Más de ochocientos millones de euros se recaudaron en pocos días para financiar su reconstrucción. Cinco años de trabajos minuciosos movilizaron a los mejores artesanos franceses: carpinteros, canteros, maestros vidrieros y organeros. Reabierta al público en diciembre de 2024, Notre-Dame acoge de nuevo a millones de visitantes que vienen a admirar su aguja restaurada, sus vitrales recuperados y su órgano monumental de cinco teclados y ocho mil tubos.`,
  de: `Notre-Dame de Paris, eine gotische Kathedrale auf der Île de la Cité im Herzen von Paris, wurde zwischen 1163 und 1345 unter der Leitung von Bischof Maurice de Sully erbaut. Als Meisterwerk mittelalterlicher Kunst zeichnet sie sich durch ihre Strebebögen, ihre ikonischen Wasserspeier und ihre drei Rosetten mit farbenfrohen Buntglasfenstern aus. Im Laufe der Jahrhunderte erlebte sie die Krönung Napoleons im Jahr 1804, inspirierte Victor Hugo zu seinem unsterblichen Roman und überstand die Französische Revolution, die sie beinahe zerstört hätte. Am 15. April 2019 verwüstete ein verheerender Brand ihr Dach und ließ ihren Turm einstürzen, was eine weltweite Welle der Solidarität auslöste. Innerhalb weniger Tage wurden über achthundert Millionen Euro gesammelt, um den Wiederaufbau zu finanzieren. Fünf Jahre sorgfältiger Arbeiten mobilisierten die besten französischen Handwerker: Zimmerleute, Steinmetze, Glasermeister und Orgelbauer. Im Dezember 2024 für die Öffentlichkeit wiedereröffnet, empfängt Notre-Dame erneut Millionen Besucher, die ihren restaurierten Turm, ihre wiedergewonnenen Buntglasfenster und ihre monumentale Orgel mit fünf Manualen und achttausend Pfeifen bewundern wollen.`,
  nl: `Notre-Dame de Paris, een gotische kathedraal gelegen op het Île de la Cité in het hart van Parijs, werd tussen 1163 en 1345 gebouwd onder leiding van bisschop Maurice de Sully. Als meesterwerk van de middeleeuwse kunst valt zij op door haar luchtbogen, haar iconische waterspuwers en haar drie rozetvensters met kleurrijk glas-in-lood. Door de eeuwen heen heeft zij de kroning van Napoleon in 1804 gehuisvest, Victor Hugo geïnspireerd tot zijn onsterfelijke roman, en de Franse Revolutie overleefd die haar bijna had vernietigd. Op 15 april 2019 verwoestte een verschrikkelijke brand haar dak en deed haar torenspits instorten, wat een wereldwijde golf van solidariteit teweegbracht. Binnen enkele dagen werd er meer dan achthonderd miljoen euro ingezameld om de wederopbouw te financieren. Vijf jaar van nauwgezet werk mobiliseerde de beste Franse ambachtslieden: timmermannen, steenhouwers, meester-glasmakers en orgelbouwers. In december 2024 weer geopend voor het publiek, ontvangt Notre-Dame opnieuw miljoenen bezoekers die haar gerestaureerde torenspits, haar herstelde gebrandschilderde ramen en haar monumentale orgel met vijf manualen en achtduizend pijpen komen bewonderen.`,
  ja: `ノートルダム大聖堂はパリのシテ島の中心に位置するゴシック様式の大聖堂であり、モーリス・ド・シュリー司教の主導のもと、1163年から1345年にかけて建造されました。中世美術の傑作として、フライング・バットレス、象徴的なガーゴイル、そして色とりどりのステンドグラスを持つ三つのバラ窓が際立っています。数世紀にわたり、1804年のナポレオン皇帝戴冠式を執り行い、ヴィクトル・ユーゴーに不朽の小説を書かせ、ほぼ取り壊されかけたフランス革命を生き延びました。2019年4月15日、壊滅的な火災が屋根を焼き尽くし、尖塔は崩落しました。これにより世界中で連帯の波が広がりました。数日のうちに八億ユーロを超える資金が再建のために集まりました。五年間の綿密な作業によって、最も優れたフランス人職人たちが集結しました。大工、石工、ステンドグラス職人、オルガン製作者です。2024年12月に再開された大聖堂は、復元された尖塔、取り戻されたステンドグラス、五段の鍵盤と八千本のパイプを持つ巨大なオルガンを鑑賞しに訪れる数百万人の人々を再び迎え入れています。`,
  zh: `巴黎圣母院是一座位于巴黎西岱岛中心的哥特式大教堂，由主教莫里斯·德·叙利主持，于公元1163年至1345年间建成。作为中世纪艺术的杰作，它以其飞扶壁、标志性的滴水兽和三扇彩色玻璃花窗而闻名。数百年来，它见证了1804年拿破仑的加冕，启发了维克多·雨果创作了不朽的小说，并经历了几乎将它摧毁的法国大革命。2019年4月15日，一场毁灭性的大火吞噬了它的屋顶，使尖塔倒塌，激起了全世界的团结浪潮。数日之内，超过八亿欧元的资金被筹集用于重建。五年的精心修复工作动员了最优秀的法国工匠：木匠、石匠、玻璃工匠和管风琴制作师。2024年12月重新向公众开放后，巴黎圣母院再次迎接数百万游客前来欣赏修复后的尖塔、重获新生的彩色玻璃，以及拥有五个键盘和八千根管的宏伟管风琴。`,
};

export function getSampleText(voice: VoiceKey): string {
  return SAMPLE_TEXTS[voice];
}
